# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-job:
    docker:
      # specify the version you desire here
     

      - image: node:8.0

        
      # - steps:
      #   # ...
      #   - run:
      #       name: Dump Google Cloud Credentials to file
      #       command: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
        # ...  
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/deploy-test

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: .
          # Must be relative path from root
          paths:
            - .

  deploy-job:

      docker:

        - image: google/cloud-sdk
  
      #working_directory: ~/deploy-test

      steps:

        - attach_workspace:
            # Must be absolute path or relative path from working_directory
            at: ~/deploy-test

        - setup_remote_docker

        - run:
            name: Install Docker client
            command: |
              set -x
              VER="17.03.0-ce"
              curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
              tar -xz -C /tmp -f /tmp/docker-$VER.tgz
              mv /tmp/docker/* /usr/bin

        - run:
            name: Dump Google Cloud Credentials to file
            command: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json

        - run:
            name: Login GoogleCloud
            command: |
              echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
              gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
              gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
              gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
              gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}

        - run:
            name: Build Docker Image and Push registry
            command: |
              TAG=0.1.$CIRCLE_BUILD_NUM
              docker build -t   gcr.io/${GOOGLE_PROJECT_ID}/deploy-test:$TAG ~/deploy-test
              gcloud docker -- push gcr.io/${GOOGLE_PROJECT_ID}/deploy-test:$TAG
              #kubectl run deploy-test --image=gcr.io/sharp7c0timesfour-174112/deploy-test:$TAG
              #kubectl expose deployment deploy-test --type="LoadBalancer" --port=80 --target-port=8080
              kubectl set image deployment/deploy-test image gcr.io/sharp7c0timesfour-174112/deploy-test:$TAG

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master

